server:
  port: 8888
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/chat?serverTimezone=Asia/Seoul
#    username: chat
#    password: chat
    url: jdbc:mysql://18.190.53.4:3306/covengers?serverTimezone=Asia/Seoul
    username: root
    password: zhqpswutm400vkdlxldA!


  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database: mysql


